# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 094cfcfd5a8a36b16749f74b3f9d157f78fc3c47d09661d0cfb86598716f3087c301f512a9d58cec6b99e8fb495e0aa6e471bb8a3a86037967cda014baa57ae2

test:
  secret_key_base: 9ced94641b5fb6a43f258a3bdd84192a6697f9d17b052da9b8c3ba790647cd78d79796c392da9b7ea3793a1e893991a55e2dd2cad73f56cf664769fd6f214cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
